# Generated by Django 5.1.6 on 2025-02-19 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='restaurant_stars',
        ),
        migrations.AddField(
            model_name='category',
            name='category_name_en',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='category_name_ru',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='food_description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='food_description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='food_name_en',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='food_name_ru',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_name_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='supplement',
            name='supplement_name_en',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='supplement',
            name='supplement_name_ru',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
