# Generated by Django 5.1.6 on 2025-02-19 08:05

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0002_remove_restaurant_restaurant_stars_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workingdays',
            name='working_days',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Понедельник', 'Понедельник'), ('Вторник', 'Вторник'), ('Среда', 'Среда'), ('Четверг', 'Четверг'), ('Пятница', 'Пятница'), ('Суббота', 'Суббота'), ('Воскресенье', 'Воскресенье')], max_length=64),
        ),
    ]
