# Generated by Django 5.1.6 on 2025-02-19 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0004_remove_food_category_food_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplement',
            name='food',
        ),
        migrations.AddField(
            model_name='supplement',
            name='food',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='supplement_food', to='menu_app.food'),
            preserve_default=False,
        ),
    ]
